# Generated by Django 3.1.5 on 2021-01-13 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toys', '0004_auto_20210113_2244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='toy',
            old_name='tag',
            new_name='tags',
        ),
    ]
